[package]
name = "iotscape"
version = "0.1.2"
edition = "2021"
authors = ["Gordon Stein"]
license = "MIT OR Apache-2.0"
description = "Library for creating IoTScape services for NetsBlox in Rust"
homepage = "https://github.com/gsteinLTU/iotscape-rs"
repository = "https://github.com/gsteinLTU/iotscape-rs"

[lib]
name = "iotscape"
crate-type = ["lib"]

[dependencies]
log = "0.4.20"
serde = { version = "1.0.152", default-features = false , features = ["derive", "alloc"] }
serde_json = { version = "1.0.91", default-features = false, features = ["alloc"] }

[dev-dependencies]
tokio = { version = "1.23.0", features = ["full"] }

[features]
std = []
default = ["std"]
